package com.github.leandrolimasi.algorithms;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

@SpringBootTest(classes = {TwoStrings.class})
public class TwoStringsTest {

  @Autowired private TwoStrings twoStrings;

  @Test
  public void testCase1() {
    boolean[] result =
        twoStrings.commonSubstring(Arrays.asList("hello", "hi"), Arrays.asList("world", "bye"));
    boolean[] expected = new boolean[] {true, false};
    assertArrayEquals(result, expected);
  }

  @Test
  public void testCase2() {
    boolean[] result =
        twoStrings.commonSubstring(
            Arrays.asList(
                "augxttdwiflnfqsjnttxwbphgvgjgtkuajymlzgvbnkxwvtlojnqbuvxqnxevsddeojzkfhdijxpylhhikdhdjezhbtpoyrrlwpcjluaiispuzhwooezhfgjhmwymlsgmbjrqfywvphtvjixrsmgnmvdsdqruxrvutdnthivxbmzrrjagmmyqttwkusamwdumzatjosswsgatdlqtjzxuzxxrdujwmrcyllobngkayzbbeuayhowqexwocikvbvpanmfufeltvltvmebvxprdhhnsfsapaieibuuunpjvtkghoanggouywbyjbaolqnrrihcvtqxqetgpkzarsqgpuwsrdxevhbmmrngoyxuulmvehatpwaenmdfceaesbbsnizdtxqcolypnyblpkwkllyccwopbzmzfftrtcqxfrxwieuodrajtuvalvwrksmukoirqgggqvvaknsfzzixhiasjpuiherpuqkccgymdbayeyfpbsnmrkqzpratahquatcysnuzszseduttcsablnbnjhtxioxsofidagkprbjubaticqousmykcyxroesflgjetmzinwpzyqjhbjskgmrbbdulctsxdkxpjpxoawacffhyjjrltcsiipzlhmdlaxyjjsmnredwhkakcmgmwrmzrniavaakavwcztkmveoesxkyiyfvagomnnjougobkorkdxblqhlxvauprkombtwhijmlrrdjzpjqgitvfvlhkgdicrjhfbzoschkommnbqzzmhcqlcznybvitolbjbpyiqvefrszqxtmigfwplxtnexrvcmmlniqgkoujkkykgndgovotnbgvlolqkomirtrkueiapyonqtmamrducfwsqhwgjhipblqsckqwjpedbldntdaclkdstvtndfhlgqoirnelm",
                "xpdeuhevbpjjaiezkrgdmsdkmrmzqfbwlmcsitcpthcbvxzqvqhuamhhapllumnqqtcgqtyweuieivcynxzzcdsbehpbikbxidpkxolvzjwmjyrxwtyiqsmqemslpmopqpwhtkyqucuxdnbpywisuyfxqdfwcbbwqwhrpbdiojfkqpdivcvmsdwrgfdfxqmwhcufwutnqzxnnsayzurrhhjavcxkcjsiariykrqcffixtcoftbkatslndrrbyaytmwzwyuqccgtndqkaaoedjyzfrfzhwmswasqzcfzvlzmwsmxqblbrjmxfugvewxzyhqxbchpeveiyibbzdnshoquvxchwmpuoejsjcwriyddwvqrdixydnvaiqhzbrwkoeentkdvktfrxueddedvcyyttwsmwlvtqmvuiqbqsrheysuloieicyxgqlxvylyburgihigbrfmxvmjrnemxkqptnmwfaqqhdxsgialqefznlizbxljggsgpacrmpqpovtggclvyzodrldzwclbgcstmptlvtiuccrncrkstryqohyotlqrcpjrafrbtadsdfewvtydicyotqixrboyupmqxbrlwppvrtroshaogjqbyeksbuaktbtaiynlfllidfxspalnqjamhmlldxufwiwdfnpbhyoqozwkrwylejohyrbldgrlmjoqsjgsvqzpyphmanhpilmdcrbqgcrmiamlhlxqjwjakonlqqrzxmvxfcjfodrwodluaaksolkxukczarajplhlokblzihybsdayyxifvjlobkvkoylytqsyoblpwwpmqxjdbwujyxipjwpsmfyugfaohscmpbzrouljrwwggdofhfrnmdrbxjeuusdacgvnhapxsiwbkaqxqrajelzlietjaqjfbjbidjbgvujbxpgcaasrxcqaemkalpaeiicllfkewie",
                "dcfwkrdbapslyhmersirjgnagrdgdjxcvkxwcvaqkluaomfymiytccxybmjpvwmxpthkmidsyqzuauxcznuylznutyyvhfjawugojzoujfrbudghrzaykjuberuhhejhvwlfylnhopyiweevmewrgcfxpkshmredyggpluwtuaeubolhkxxoendpmxsbpqxrueyeilhqznmhtwiinnfvqiidujizulzktrgstfcfqoufoljzhfdvlqwdesfefjvxfqkiwcjebdwfykxlmjbaiqdehoqjqwskbldpihvcbuiisweglqfmzoiajtlzbpjlypuszjppqngdpyadwqcnuyphlmooqwipnabjgfuunnyrqkttxefznldmagyivjulvclbulphopjviukjyexpmtmjoydpqlvnnbyeycwvycieexjvcixoynilbixzkxzswahuzckazfcfilqpkyvjyfayyxpqtqkncstiizwilheqlxaesokmivoxirzjvvkbfrwaspndqfrqxlyopjjinyzpimedsoqstrrefgleekcuevneuvapvuiejbtowjamsqszccybtotlabmubyeuqzabeitndcrpbpazjctbroopfjygridmtwwspvjxgpoetnvydzywuinnsfvzxpklzebaxjuncvtlxyzrxbhbqostfzxahucqmzmgzrgopjwtxqmwvpalssmpiwmedhllhdwstonfjrywciuvhbylqqnobbzaphkqcvmilgnqhpjkbnurwgsfrkfmfvergymamwwqobjhiftefolaofzesexikfblpxgqgmkivrtyqtluthqhgzqx"),
            Arrays.asList(
                "pyhqhnibfqxfzyfojddppodiwgncxerswvhamtdshqhwrlowwpknepgsqaqlinhprlhrqwyhxmuahrpgpaxccwhaglhtayvldimqlqubzavgepjjrcwoqpxuevzytjoioiupwinzzwubpmujadrzhwdskolfkrncrdlgndrihnbrhuawzzyxnojosovujptkrorunpdexogsycsntufbrflbckcvfnjccxlftbiwjqgaltmunhadehcxjbqobiijhftqpdnjgdoalqatwgmhqgheglfhcxepvbpmctnwnawqehvujwpditebxvmwliqqaylpyzlmwzryzfxbbsttyrhuczzcmrhfjfipnchgjsoxspudutdvkouqpwnrnrdelihsjtioayszqkptzqmsdmcsrewpxenpgymxstltijaoidhqbatiibuiuqjyncbkvepaqjmvkvudooywbhbznjcsrqqffeotvygwrjclwuqdqkzomuohrobawdbbtxxfiisbykxvkbxefwyeqovklhpeeyzoqojxogntzlhdftkpzscikrppbiuzcwkvwfnzmnswugzxwciptkcrkbdqplwokscwhejnvgywoahvzpbwjkbgryktnthsbnnqoxjrbabbedylryrijlouvkjwyxhnyefghhiypesaosrspczjawgkzdmomqhrcomydsyfwadlbkjrptmxmbtjblrohrjsylzqmcjdxeatwifwwuhzafznfepcsrmdhuysdtmpmavincpjohcscdshvnnbyiaqeyqnnzkzthyvxkmlolyhzwhktwastxrpjgpbtsbwkioexzbtexrbwsjxhnfncdbjoztaiuvzasjlrpqghpwakumypekiurjgqqoxpluzxszcmgxqwamzgkmsrwjvfnixkdokse",
                "dcbyewkqpirreeiptnfbhvrcqcxzdqztcwvraecnikflgwzucnsawlhfawpptawblyuqivtveumselhesspwnglosezhhzwdaehrqonnyfgkfykluhkpqzfhmbeiycvxhltbxdqhfnymkbeqahvtzovrerxzrwbulxnadnfqeuiygrcmcvwvxnpjulxougmtbpukjlmmdrawisrjtvrqvypfsrbdqjbrbxqhvndupusngyvoqeakzoxrtrlsbwvjqeuduebfrdynhixytkyfnluoenpedekqtbbsfwtzgohtlbeuvfzbrapezatjfzlvekocbmszgcljcffyrvlbikqftepaoytxekvcwpjkyymqenipsykyejamhyulwflsueggmlddpcgfxcvtbgcikvqfcjmodfblrepotoxvxwuthitsntjirxneneegntthflzgxgwowucnamevfqdszwublfpgzomenizotyambxlfweevfolltsgoygmsnerzpvnkxmvtuewvuafrcmwgwslhvmnoiknmsnnjhwnysapdwsbakluphnwptvhbnsftqoepqycjafchrxnpuetesowgjyvqqiezalpjvslcrqfwqznjstwocgnidhflddkqgwbpfjamhofkefvdbvjmsaqsmrrdhvtadniciramsvvzhejopqyahkqhxfubdjtpwexpqoziqacrfatlyrkajuhwftlxitbexwryzvisirzgbmgjyvytmbppnkafmzarqensvtqoupmilbbpaualanlkdqfnswqywohvddmklkrzatjbwanyrceqinxpgbnifxwtthaogtoqfjtnylwwiabwpszhvxqhqkmppjlstkdbtvntitzguygocqtfpqpuslvaamczifwsxbfzhoemeeossrrsservdrtmwwglreogedgcmebaukcwyz",
                "terdptlntydffrjwbxwjqevwqbdcenrnmiovbeaobqsmmnptrrdpddgmsfpazhvltwzkoflfevhdxwqcrxmdctmtmcaekdtxgazntwcuahesftnhsurhkbazmmcagdymnunxbmvfxtzrkqnbevlgyahitfximywsblgqgrdlljesjlncsshxsqjdkrhodknpsibttmilbusapohjgjgshvzurfeypagzlochqltitvailrfczymoqcadawvhaexqnokmbtjevsyrmjikcieksxiwfwrjhvoqegaqzqbqranadwixsoblmibyrfbhkgogmrftovwwvboonxwkmhhyypgkfvleihzysgvagcuxptwzgzaiqpgitnhddvohjtegmnjftggksaokglldmwefilkiuegndbptuxksydstzlquzlymsldeufciajitzjhhgbgeacmwsnukpdeycppmdnlpjngbweobomethqocetvttjsgmbwkpvpotxxtrtsxwwyebjudfpbyoodnvxrqqdzrqigzikhjbzgidbsijzxtysxyqnnbogykovqkjwsadijtcbclqkodaqbacaohdrowbfxojvwpmjztctrsunprxzggameiqmurelnhwtzxhjvbkdfnqmgdyeyorudxcxewgjslvdotyojynzqyppprrrlhocyetkcnhskzgbkoffzeqlfvhqbyrqwximhrjxhpvkrkxwjroohtancuxyqutfuiowhfpsepurzccgmolfkzduyruvhpgigzcsblhniaulqlhpfhhrqyqbvzpeeffddfqaiwctehpkvkmxwgpikirrge"));
    boolean[] expected = new boolean[] {true, true, true};
    assertArrayEquals(result, expected);
  }
}
