package com.github.leandrolimasi.algorithms;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.Arrays;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = {TwoStrings.class})
public class TwoStringsTest {

  @Autowired private TwoStrings twoStrings;

  @Test
  public void testCase1() {
    twoStrings.commonSubstring(Arrays.asList("hello", "hi"), Arrays.asList("world", "bye"));
  }

  @Test
  public void testCase2() {
    twoStrings.commonSubstring(
        Arrays.asList(
            "augxttdwiflnfqsjnttxwbphgvgjgtkuajymlzgvbnkxwvtlojnqbuvxqnxevsddeojzkfhdijxpylhhikdhdjezhbtpoyrrlwpcjluaiispuzhwooezhfgjhmwymlsgmbjrqfywvphtvjixrsmgnmvdsdqruxrvutdnthivxbmzrrjagmmyqttwkusamwdumzatjosswsgatdlqtjzxuzxxrdujwmrcyllobngkayzbbeuayhowqexwocikvbvpanmfufeltvltvmebvxprdhhnsfsapaieibuuunpjvtkghoanggouywbyjbaolqnrrihcvtqxqetgpkzarsqgpuwsrdxevhbmmrngoyxuulmvehatpwaenmdfceaesbbsnizdtxqcolypnyblpkwkllyccwopbzmzfftrtcqxfrxwieuodrajtuvalvwrksmukoirqgggqvvaknsfzzixhiasjpuiherpuqkccgymdbayeyfpbsnmrkqzpratahquatcysnuzszseduttcsablnbnjhtxioxsofidagkprbjubaticqousmykcyxroesflgjetmzinwpzyqjhbjskgmrbbdulctsxdkxpjpxoawacffhyjjrltcsiipzlhmdlaxyjjsmnredwhkakcmgmwrmzrniavaakavwcztkmveoesxkyiyfvagomnnjougobkorkdxblqhlxvauprkombtwhijmlrrdjzpjqgitvfvlhkgdicrjhfbzoschkommnbqzzmhcqlcznybvitolbjbpyiqvefrszqxtmigfwplxtnexrvcmmlniqgkoujkkykgndgovotnbgvlolqkomirtrkueiapyonqtmamrducfwsqhwgjhipblqsckqwjpedbldntdaclkdstvtndfhlgqoirnelm",
            "xpdeuhevbpjjaiezkrgdmsdkmrmzqfbwlmcsitcpthcbvxzqvqhuamhhapllumnqqtcgqtyweuieivcynxzzcdsbehpbikbxidpkxolvzjwmjyrxwtyiqsmqemslpmopqpwhtkyqucuxdnbpywisuyfxqdfwcbbwqwhrpbdiojfkqpdivcvmsdwrgfdfxqmwhcufwutnqzxnnsayzurrhhjavcxkcjsiariykrqcffixtcoftbkatslndrrbyaytmwzwyuqccgtndqkaaoedjyzfrfzhwmswasqzcfzvlzmwsmxqblbrjmxfugvewxzyhqxbchpeveiyibbzdnshoquvxchwmpuoejsjcwriyddwvqrdixydnvaiqhzbrwkoeentkdvktfrxueddedvcyyttwsmwlvtqmvuiqbqsrheysuloieicyxgqlxvylyburgihigbrfmxvmjrnemxkqptnmwfaqqhdxsgialqefznlizbxljggsgpacrmpqpovtggclvyzodrldzwclbgcstmptlvtiuccrncrkstryqohyotlqrcpjrafrbtadsdfewvtydicyotqixrboyupmqxbrlwppvrtroshaogjqbyeksbuaktbtaiynlfllidfxspalnqjamhmlldxufwiwdfnpbhyoqozwkrwylejohyrbldgrlmjoqsjgsvqzpyphmanhpilmdcrbqgcrmiamlhlxqjwjakonlqqrzxmvxfcjfodrwodluaaksolkxukczarajplhlokblzihybsdayyxifvjlobkvkoylytqsyoblpwwpmqxjdbwujyxipjwpsmfyugfaohscmpbzrouljrwwggdofhfrnmdrbxjeuusdacgvnhapxsiwbkaqxqrajelzlietjaqjfbjbidjbgvujbxpgcaasrxcqaemkalpaeiicllfkewie",
            "dcfwkrdbapslyhmersirjgnagrdgdjxcvkxwcvaqkluaomfymiytccxybmjpvwmxpthkmidsyqzuauxcznuylznutyyvhfjawugojzoujfrbudghrzaykjuberuhhejhvwlfylnhopyiweevmewrgcfxpkshmredyggpluwtuaeubolhkxxoendpmxsbpqxrueyeilhqznmhtwiinnfvqiidujizulzktrgstfcfqoufoljzhfdvlqwdesfefjvxfqkiwcjebdwfykxlmjbaiqdehoqjqwskbldpihvcbuiisweglqfmzoiajtlzbpjlypuszjppqngdpyadwqcnuyphlmooqwipnabjgfuunnyrqkttxefznldmagyivjulvclbulphopjviukjyexpmtmjoydpqlvnnbyeycwvycieexjvcixoynilbixzkxzswahuzckazfcfilqpkyvjyfayyxpqtqkncstiizwilheqlxaesokmivoxirzjvvkbfrwaspndqfrqxlyopjjinyzpimedsoqstrrefgleekcuevneuvapvuiejbtowjamsqszccybtotlabmubyeuqzabeitndcrpbpazjctbroopfjygridmtwwspvjxgpoetnvydzywuinnsfvzxpklzebaxjuncvtlxyzrxbhbqostfzxahucqmzmgzrgopjwtxqmwvpalssmpiwmedhllhdwstonfjrywciuvhbylqqnobbzaphkqcvmilgnqhpjkbnurwgsfrkfmfvergymamwwqobjhiftefolaofzesexikfblpxgqgmkivrtyqtluthqhgzqx"),
        Arrays.asList(
            "pyhqhnibfqxfzyfojddppodiwgncxerswvhamtdshqhwrlowwpknepgsqaqlinhprlhrqwyhxmuahrpgpaxccwhaglhtayvldimqlqubzavgepjjrcwoqpxuevzytjoioiupwinzzwubpmujadrzhwdskolfkrncrdlgndrihnbrhuawzzyxnojosovujptkrorunpdexogsycsntufbrflbckcvfnjccxlftbiwjqgaltmunhadehcxjbqobiijhftqpdnjgdoalqatwgmhqgheglfhcxepvbpmctnwnawqehvujwpditebxvmwliqqaylpyzlmwzryzfxbbsttyrhuczzcmrhfjfipnchgjsoxspudutdvkouqpwnrnrdelihsjtioayszqkptzqmsdmcsrewpxenpgymxstltijaoidhqbatiibuiuqjyncbkvepaqjmvkvudooywbhbznjcsrqqffeotvygwrjclwuqdqkzomuohrobawdbbtxxfiisbykxvkbxefwyeqovklhpeeyzoqojxogntzlhdftkpzscikrppbiuzcwkvwfnzmnswugzxwciptkcrkbdqplwokscwhejnvgywoahvzpbwjkbgryktnthsbnnqoxjrbabbedylryrijlouvkjwyxhnyefghhiypesaosrspczjawgkzdmomqhrcomydsyfwadlbkjrptmxmbtjblrohrjsylzqmcjdxeatwifwwuhzafznfepcsrmdhuysdtmpmavincpjohcscdshvnnbyiaqeyqnnzkzthyvxkmlolyhzwhktwastxrpjgpbtsbwkioexzbtexrbwsjxhnfncdbjoztaiuvzasjlrpqghpwakumypekiurjgqqoxpluzxszcmgxqwamzgkmsrwjvfnixkdokse",
            "dcbyewkqpirreeiptnfbhvrcqcxzdqztcwvraecnikflgwzucnsawlhfawpptawblyuqivtveumselhesspwnglosezhhzwdaehrqonnyfgkfykluhkpqzfhmbeiycvxhltbxdqhfnymkbeqahvtzovrerxzrwbulxnadnfqeuiygrcmcvwvxnpjulxougmtbpukjlmmdrawisrjtvrqvypfsrbdqjbrbxqhvndupusngyvoqeakzoxrtrlsbwvjqeuduebfrdynhixytkyfnluoenpedekqtbbsfwtzgohtlbeuvfzbrapezatjfzlvekocbmszgcljcffyrvlbikqftepaoytxekvcwpjkyymqenipsykyejamhyulwflsueggmlddpcgfxcvtbgcikvqfcjmodfblrepotoxvxwuthitsntjirxneneegntthflzgxgwowucnamevfqdszwublfpgzomenizotyambxlfweevfolltsgoygmsnerzpvnkxmvtuewvuafrcmwgwslhvmnoiknmsnnjhwnysapdwsbakluphnwptvhbnsftqoepqycjafchrxnpuetesowgjyvqqiezalpjvslcrqfwqznjstwocgnidhflddkqgwbpfjamhofkefvdbvjmsaqsmrrdhvtadniciramsvvzhejopqyahkqhxfubdjtpwexpqoziqacrfatlyrkajuhwftlxitbexwryzvisirzgbmgjyvytmbppnkafmzarqensvtqoupmilbbpaualanlkdqfnswqywohvddmklkrzatjbwanyrceqinxpgbnifxwtthaogtoqfjtnylwwiabwpszhvxqhqkmppjlstkdbtvntitzguygocqtfpqpuslvaamczifwsxbfzhoemeeossrrsservdrtmwwglreogedgcmebaukcwyz",
            "terdptlntydffrjwbxwjqevwqbdcenrnmiovbeaobqsmmnptrrdpddgmsfpazhvltwzkoflfevhdxwqcrxmdctmtmcaekdtxgazntwcuahesftnhsurhkbazmmcagdymnunxbmvfxtzrkqnbevlgyahitfximywsblgqgrdlljesjlncsshxsqjdkrhodknpsibttmilbusapohjgjgshvzurfeypagzlochqltitvailrfczymoqcadawvhaexqnokmbtjevsyrmjikcieksxiwfwrjhvoqegaqzqbqranadwixsoblmibyrfbhkgogmrftovwwvboonxwkmhhyypgkfvleihzysgvagcuxptwzgzaiqpgitnhddvohjtegmnjftggksaokglldmwefilkiuegndbptuxksydstzlquzlymsldeufciajitzjhhgbgeacmwsnukpdeycppmdnlpjngbweobomethqocetvttjsgmbwkpvpotxxtrtsxwwyebjudfpbyoodnvxrqqdzrqigzikhjbzgidbsijzxtysxyqnnbogykovqkjwsadijtcbclqkodaqbacaohdrowbfxojvwpmjztctrsunprxzggameiqmurelnhwtzxhjvbkdfnqmgdyeyorudxcxewgjslvdotyojynzqyppprrrlhocyetkcnhskzgbkoffzeqlfvhqbyrqwximhrjxhpvkrkxwjroohtancuxyqutfuiowhfpsepurzccgmolfkzduyruvhpgigzcsblhniaulqlhpfhhrqyqbvzpeeffddfqaiwctehpkvkmxwgpikirrge"));
  }
}
